services:
  - type: web
    name: django-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bibliometric_backend.wsgi
    envVars:
      - key: SECRET_KEY
        value: tu-clave-secreta
      - key: DEBUG
        value: false
